inherit_gem:
  scc-codestyle:
    - default.yml

inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Include:
    - Gemfile
    - Rakefile
    - config.ru
    - '**/*.rake'
  Exclude:
    - .bundle/**/*
    - db/schema.rb
    - features/**/*
    - vendor/**/*
    - tmp/**/*
    - lib/locale/*
    - package/*

Naming/FileName:
  Exclude:
    - Dangerfile

Rails/Output:
  Exclude:
    - lib/rmt/cli/**/*

Naming/UncommunicativeMethodParamName:
  AllowedNames:
  - to
  - id

RSpec/NestedGroups:
  MaxNesting: 4
