language: ruby
rvm:
  # SLES15 sp0
  - 2.4.1

  # Future versions
  - ruby-head
script:
  - 'bundle exec rails db:migrate RAILS_ENV=test'
  - 'bundle exec rspec spec'
  - 'bundle exec rubocop'
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE rmt_test;'
  - mysql -e $'GRANT ALL PRIVILEGES ON `rmt\_%` .  * TO rmt@localhost identified by \'rmt\';'
  - ruby -e "require 'yaml'; puts({'database_test'=>{'host'=>'localhost','username'=>'rmt','password'=>'rmt','database'=>'rmt_test','adapter'=>'mysql2','encoding'=>'utf8','timeout'=>5000,'pool'=>5}}.to_yaml)" > config/rmt.local.yml
