database:
  host: localhost
  username: rmt
  password:
  adapter: mysql2
  encoding: utf8
  timeout: 5000
  pool: 5

scc:
  username:
  password:

mirroring:
  base_dir: /srv/www/rmt/public/repo/
  mirror_url_prefix: /repo/
  mirror_src: false
  verify_rpm_checksums: false

http_client:
  verbose: false
  proxy:
  proxy_auth:
  proxy_user:
  proxy_password:

