
name: RMT Integration tests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    services:
      mysql:
        image: mariadb:latest
        ports:
          - "3306:3306"
        env:
          MARIADB_HOST: 127.0.0.1
          MARIADB_DATABASE: rmt_test
          MARIADB_USER: rmt
          MARIADB_PASSWORD: rmt

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        ruby-version: ['2.5.8', '2.6.6', '2.7.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
        bundler: 1.17
    - name: Gem cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ matrix.ruby-version }}-gems-${{ hashFiles('Gemfile') }}
        restore-keys: |
          ${{ matrix.ruby-version }}-gems-${{ hashFiles('Gemfile') }}
    - name: Pre-run inline scripts
      run: |
        ruby -e "require 'yaml'; puts({'database_test'=>{'host'=>'0.0.0.0','username'=>'rmt','password'=>'rmt','database'=>'rmt_test','adapter'=>'mysql2','encoding'=>'utf8','timeout'=>5000,'pool'=>5}}.to_yaml)" > config/rmt.local.yml
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 0.0.0.0 --port ${{ job.services.mysql.ports['3306'] }} -u rmt -p rmt -e "SHOW DATABASES"
    - name: Run Danger
      uses: MeilCli/danger-action@v5
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        plugins_file: 'Gemfile'
        install_path: 'vendor/bundle'
        danger_file: 'Dangerfile'
        danger_id: 'danger-pr'
    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rails db:migrate
        bundle exec rake test

